# version: "3.3"
services:
  clapclass:
    image: dmitriynazarov/clapclass:1.0.1
    container_name: clapclass
    ports:
      - "5600:5600"
#      - 8051:8051
    volumes:
      - ./files:/files
      - ./logs:/logs
    restart: always
    environment:
      JAVA_OPTS: >
        -XX:NativeMemoryTracking=summary
        -XX:+UseSerialGC
        -XX:+StartAttachListener
        -XX:MinRAMPercentage=20.0
        -XX:MaxRAMPercentage=80.0
        -Xss512k
        -Xms256m
        -Xmx3036m
#        -Dspring.profiles.active=local
#        -Dcom.sun.management.jmxremote
#        -Dcom.sun.management.jmxremote.local.only=false
#        -Dcom.sun.management.jmxremote.authenticate=false
#        -Dcom.sun.management.jmxremote.ssl=false
#        -Dcom.sun.management.jmxremote.port=8051
#        -Dcom.sun.management.jmxremote.rmi.port=8051
#        -Djava.rmi.server.hostname=localhost