<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="ru">
<head>
    <meta content="text/html; charset=utf-8" http-equiv="Content-Type">
    <meta content="width=device-width" name="viewport">

    <style>body {
            width: 100% !important;
            min-width: 100%;
            -webkit-text-size-adjust: 100%;
            -ms-text-size-adjust: 100%;
            margin: 0;
            padding: 0;
        }

        body {
            background-color: #fafafa;
            background-repeat: repeat;
            background-position: center top;
        }

        body {
            color: #222222;
            font-family: Helvetica, Arial, sans-serif;
            font-weight: normal;
            font-size: 14px;
            padding: 0;
            margin: 0;
            text-align: left;
            line-height: 1.3;
        }

        a:hover {
            color: #2795b6;
        }

        a:active {
            color: #2795b6;
        }

        a:visited {
            color: #2ba6cb;
        }

        h1 a:active {
            color: #2ba6cb !important;
        }

        h2 a:active {
            color: #2ba6cb !important;
        }

        h3 a:active {
            color: #2ba6cb !important;
        }

        h4 a:active {
            color: #2ba6cb !important;
        }

        h5 a:active {
            color: #2ba6cb !important;
        }

        h6 a:active {
            color: #2ba6cb !important;
        }

        h1 a:visited {
            color: #2ba6cb !important;
        }

        h2 a:visited {
            color: #2ba6cb !important;
        }

        h3 a:visited {
            color: #2ba6cb !important;
        }

        h4 a:visited {
            color: #2ba6cb !important;
        }

        h5 a:visited {
            color: #2ba6cb !important;
        }

        h6 a:visited {
            color: #2ba6cb !important;
        }

        table.secondary:hover td {
            background: #d0d0d0 !important;
            color: #555555;
        }

        table.secondary:hover td a {
            color: #555555 !important;
        }

        table.secondary td a:visited {
            color: #555555 !important;
        }

        table.secondary:active td a {
            color: #555555 !important;
        }

        table.success:hover td {
            background: #457a1a !important;
        }

        table.alert:hover td {
            background: #970b0e !important;
        }

        body.outlook p {
            display: inline !important;
        }

        @media only screen and (min-width: 768px) {
            table.container {
                width: 580px !important;
            }

        }

        @media only screen and (max-width: 600px) {
            .mail img {
                max-width: 100% !important;
                max-height: 100% !important;
                padding: 0 !important;
                width: auto !important;
                height: auto !important;
            }

            .mail .social img {
                width: inherit !important;
            }

            .mail center {
                min-width: 0 !important;
            }

            .mail .container {
                width: 100% !important;
            }

            .mail .row {
                width: 100% !important;
                display: block !important;
            }

            .mail .wrapper {
                display: block !important;
                padding-right: 0 !important;
            }

            .mail .columns {
                table-layout: fixed !important;
                float: none !important;
                width: 100% !important;
                padding-right: 0 !important;
                padding-left: 0 !important;
                display: block !important;
            }

            .mail .wrapper.first .columns {
                display: table !important;
            }

            .mail table.columns > tbody > tr > td {
                width: 100% !important;
                padding-left: 0 !important;
                padding-right: 0 !important;
            }

            .mail table.column > tbody > tr > td {
                width: 100% !important;
                padding-left: 0 !important;
                padding-right: 0 !important;
            }

            .mail table.columns td.expander {
                width: 1px !important;
            }

        }
    </style>
    <title></title>
</head>
<body style="width: 100% !important; min-width: 100%; -webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; color: #222222; font-family: Helvetica, Arial, sans-serif; font-weight: normal; font-size: 14px; text-align: left; line-height: 1.3; background: #fafafa repeat center top; margin: 0; padding: 0;"
>
<table class="mail"
       style="border-spacing: 0; border-collapse: collapse; vertical-align: top; text-align: left; height: 100%; width: 100%; color: #222222; font-family: Helvetica, Arial, sans-serif; font-weight: normal; font-size: 14px; line-height: 1.3; background: #fafafa repeat center top; margin: 0; padding: 0;"
>
    <tbody>
    <tr style="vertical-align: top; text-align: left; padding: 0;">
        <td class="center"
            style="word-break: break-word; -webkit-hyphens: none; -moz-hyphens: none; hyphens: none; border-collapse: collapse !important; vertical-align: top; text-align: center; color: #222222; font-family: Helvetica, Arial, sans-serif; font-weight: normal; font-size: 14px; margin: 0; padding: 0;">
            <div style="width: 100%; min-width: 580px; text-align: center;">
                <table class="container"
                       style="border-spacing: 0; border-collapse: collapse; vertical-align: top; text-align: inherit; max-width: 580px; margin: 0 auto; padding: 0;">
                    <tbody>
                    <tr style="vertical-align: top; text-align: left; padding: 0;">
                        <td style="word-break: break-word; -webkit-hyphens: none; -moz-hyphens: none; hyphens: none; border-collapse: collapse !important; vertical-align: top; text-align: left; color: #222222; font-family: Helvetica, Arial, sans-serif; font-weight: normal; font-size: 14px; margin: 0; padding: 0;"
                        >
                            <table class="row"
                                   style="border-spacing: 0; border-collapse: collapse; vertical-align: top; text-align: left; width: 100%; position: relative; display: block; background: transparent repeat center top; padding: 0;"
                            >
                                <tbody>
                                <tr style="vertical-align: top; text-align: left; padding: 0;">
                                    <td class="wrapper first last"
                                        style="word-break: break-word; -webkit-hyphens: none; -moz-hyphens: none; hyphens: none; border-collapse: collapse !important; vertical-align: top; text-align: left; position: relative; color: #222222; font-family: Helvetica, Arial, sans-serif; font-weight: normal; font-size: 14px; margin: 0; padding: 0;"
                                    >
                                        <table class="twelve columns"
                                               style="border-spacing: 0; border-collapse: collapse; vertical-align: top; text-align: left; width: 580px; margin: 0 auto; padding: 0;">
                                            <tbody>
                                            <tr style="vertical-align: top; text-align: left; padding: 0;">
                                                <td style="word-break: break-word; -webkit-hyphens: none; -moz-hyphens: none; hyphens: none; border-collapse: collapse !important; vertical-align: top; text-align: left; width: 100%; color: #222222; font-family: Helvetica, Arial, sans-serif; font-weight: normal; font-size: 14px; margin: 0; padding: 0;"
                                                >
                                                    <table style="width: 100%; border-spacing: 0; border-collapse: collapse; vertical-align: top; text-align: left; padding: 0;">
                                                        <tbody>
                                                        <tr style="vertical-align: top; text-align: left; padding: 0;"
                                                        >
                                                            <td class=""
                                                                style="font-size: 1px; line-height: 0; word-break: break-word; -webkit-hyphens: none; -moz-hyphens: none; hyphens: none; border-collapse: collapse !important; vertical-align: top; text-align: left; width: 100%; color: #222222; font-family: Helvetica, Arial, sans-serif; font-weight: normal; background: transparent repeat center center; margin: 0; padding: 20px 0 0;"
                                                            >&nbsp;
                                                            </td>
                                                        </tr>
                                                        </tbody>
                                                    </table>


                                                </td>
                                                <td class="expander"
                                                    style="word-break: break-word; -webkit-hyphens: none; -moz-hyphens: none; hyphens: none; border-collapse: collapse !important; vertical-align: top; text-align: left; width: 100%; visibility: hidden; color: #222222; font-family: Helvetica, Arial, sans-serif; font-weight: normal; font-size: 14px; margin: 0; padding: 0;"
                                                ></td>
                                            </tr>
                                            </tbody>
                                        </table>
                                    </td>

                                </tr>
                                </tbody>
                            </table>
                        </td>
                    </tr>
                    </tbody>
                </table>

                <table class="container"
                       style="border-spacing: 0; border-collapse: collapse; vertical-align: top; text-align: inherit; max-width: 580px; margin: 0 auto; padding: 0;">
                    <tbody>
                    <tr style="vertical-align: top; text-align: left; padding: 0;">
                        <td style="word-break: break-word; -webkit-hyphens: none; -moz-hyphens: none; hyphens: none; border-collapse: collapse !important; vertical-align: top; text-align: left; color: #222222; font-family: Helvetica, Arial, sans-serif; font-weight: normal; font-size: 14px; margin: 0; padding: 0;"
                        >
                            <table class="row"
                                   style="border-radius: 11px; -webkit-border-radius: 11px; -moz-border-radius: 11px; border-spacing: 0; border-collapse: collapse; vertical-align: top; text-align: left; width: 100%; position: relative; display: block; background: #ffffff repeat center top; padding: 5px 0;"
                                  >
                                <tbody>
                                <tr style="vertical-align: top; text-align: left; padding: 0;">
                                    <td class="wrapper first last"
                                        style="word-break: break-word; -webkit-hyphens: none; -moz-hyphens: none; hyphens: none; border-collapse: collapse !important; vertical-align: top; text-align: left; position: relative; color: #222222; font-family: Helvetica, Arial, sans-serif; font-weight: normal; font-size: 14px; margin: 0; padding: 0;"
                                    >
                                        <table class="twelve columns"
                                               style="border-spacing: 0; border-collapse: collapse; vertical-align: top; text-align: left; width: 580px; margin: 0 auto; padding: 0;">
                                            <tbody>
                                            <tr style="vertical-align: top; text-align: left; padding: 0;">
                                                <td style="word-break: break-word; -webkit-hyphens: none; -moz-hyphens: none; hyphens: none; border-collapse: collapse !important; vertical-align: top; text-align: left; width: 100%; color: #222222; font-family: Helvetica, Arial, sans-serif; font-weight: normal; font-size: 14px; margin: 0; padding: 0;"
                                                >
                                                    <table class="table-block"
                                                           style="border-spacing: 0; border-collapse: collapse; vertical-align: top; text-align: left; padding: 0;">
                                                        <tbody>
                                                        <tr style="vertical-align: top; text-align: left; padding: 0;"
                                                        >
                                                            <td class=""
                                                                style="word-break: break-word; -webkit-hyphens: none; -moz-hyphens: none; hyphens: none; border-collapse: collapse !important; vertical-align: top; text-align: left; width: 100%; color: #222222; font-family: Helvetica, Arial, sans-serif; font-weight: normal; font-size: 14px; background: transparent repeat center center; margin: 0; padding: 0 10px;"
                                                            >
                                                                <p style="text-align: left; color: #222222; font-family: Helvetica, Arial, sans-serif; font-weight: normal; font-size: 14px; line-height: 1.3; margin: 0 0 10px; padding: 0;"
                                                                ><span
                                                                            style="font-size: 20px; font-family: Arial, sans-serif;"><strong>Восстановление пароля</strong></span>
                                                                </p>
                                                                <p style="text-align: left; color: #222222; font-family: Helvetica, Arial, sans-serif; font-weight: normal; font-size: 14px; line-height: 1.3; margin: 0 0 10px; padding: 0;"
                                                                ><span style="font-size: 18px;">Вы успешно востановили пароль.</span>
                                                                </p>
                                                                <p style="text-align: left; color: #222222; font-family: Helvetica, Arial, sans-serif; font-weight: normal; font-size: 14px; line-height: 1.3; margin: 0 0 10px; padding: 0;"
                                                                >
                                                                    <span style="font-size: 18px;">Новый пароль: ${password}</span><br>&nbsp;<br>&nbsp;
                                                                </p>
                                                                <p style="text-align: left; color: #222222; font-family: Helvetica, Arial, sans-serif; font-weight: normal; font-size: 14px; line-height: 1.3; margin: 0 0 10px; padding: 0;"
                                                                >&nbsp;</p>
                                                            </td>
                                                        </tr>
                                                        </tbody>
                                                    </table>


                                                </td>
                                                <td class="expander"
                                                    style="word-break: break-word; -webkit-hyphens: none; -moz-hyphens: none; hyphens: none; border-collapse: collapse !important; vertical-align: top; text-align: left; width: 100%; visibility: hidden; color: #222222; font-family: Helvetica, Arial, sans-serif; font-weight: normal; font-size: 14px; margin: 0; padding: 0;"
                                                ></td>
                                            </tr>
                                            </tbody>
                                        </table>
                                    </td>

                                </tr>
                                </tbody>
                            </table>
                        </td>
                    </tr>
                    </tbody>
                </table>


            </div>
        </td>
    </tr>
    </tbody>
</table>


</body>
</html>