<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="ru">
<head>
    <meta content="text/html; charset=utf-8" http-equiv="Content-Type">
    <meta content="width=device-width" name="viewport">

    <style>body {
            width: 100% !important;
            min-width: 100%;
            -webkit-text-size-adjust: 100%;
            -ms-text-size-adjust: 100%;
            margin: 0;
            padding: 0;
        }

        body {
            background-color: #fafafa;
            background-repeat: repeat;
            background-position: center top;
        }

        body {
            color: #222222;
            font-family: Helvetica, Arial, sans-serif;
            font-weight: normal;
            font-size: 14px;
            padding: 0;
            margin: 0;
            text-align: left;
            line-height: 1.3;
        }

        a:hover {
            color: #2795b6;
        }

        a:active {
            color: #2795b6;
        }

        a:visited {
            color: #2ba6cb;
        }

        h1 a:active {
            color: #2ba6cb !important;
        }

        h2 a:active {
            color: #2ba6cb !important;
        }

        h3 a:active {
            color: #2ba6cb !important;
        }

        h4 a:active {
            color: #2ba6cb !important;
        }

        h5 a:active {
            color: #2ba6cb !important;
        }

        h6 a:active {
            color: #2ba6cb !important;
        }

        h1 a:visited {
            color: #2ba6cb !important;
        }

        h2 a:visited {
            color: #2ba6cb !important;
        }

        h3 a:visited {
            color: #2ba6cb !important;
        }

        h4 a:visited {
            color: #2ba6cb !important;
        }

        h5 a:visited {
            color: #2ba6cb !important;
        }

        h6 a:visited {
            color: #2ba6cb !important;
        }

        table.secondary:hover td {
            background: #d0d0d0 !important;
            color: #555555;
        }

        table.secondary:hover td a {
            color: #555555 !important;
        }

        table.secondary td a:visited {
            color: #555555 !important;
        }

        table.secondary:active td a {
            color: #555555 !important;
        }

        table.success:hover td {
            background: #457a1a !important;
        }

        table.alert:hover td {
            background: #970b0e !important;
        }

        body.outlook p {
            display: inline !important;
        }

        @media only screen and (min-width: 768px) {
            table.container {
                width: 580px !important;
            }
        }

        @media only screen and (max-width: 600px) {
            .mail img {
                max-width: 100% !important;
                max-height: 100% !important;
                padding: 0 !important;
                width: auto !important;
                height: auto !important;
            }

            .mail .social img {
                width: inherit !important;
            }

            .mail center {
                min-width: 0 !important;
            }

            .mail .container {
                width: 100% !important;
            }

            .mail .row {
                width: 100% !important;
                display: block !important;
            }

            .mail .wrapper {
                display: block !important;
                padding-right: 0 !important;
            }

            .mail .columns {
                table-layout: fixed !important;
                float: none !important;
                width: 100% !important;
                padding-right: 0 !important;
                padding-left: 0 !important;
                display: block !important;
            }

            .mail .wrapper.first .columns {
                display: table !important;
            }

            .mail table.columns > tbody > tr > td {
                width: 100% !important;
                padding-left: 0 !important;
                padding-right: 0 !important;
            }

            .mail table.column > tbody > tr > td {
                width: 100% !important;
                padding-left: 0 !important;
                padding-right: 0 !important;
            }
        }
    </style>
    <title></title>
</head>
<body style="width: 100% !important; min-width: 100%; -webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; color: #222222; font-family: Helvetica, Arial, sans-serif; font-weight: normal; font-size: 14px; text-align: left; line-height: 1.3; background: #fafafa repeat center top; margin: 0; padding: 0;"
>
<table class="mail"
       style="border-spacing: 0; border-collapse: collapse; vertical-align: top; text-align: left; height: 100%; width: 100%; color: #222222; font-family: Helvetica, Arial, sans-serif; font-weight: normal; font-size: 14px; line-height: 1.3; background: #fafafa repeat center top; margin: 0; padding: 0;"
>
    <tbody>
    <tr style="vertical-align: top; text-align: left; padding: 0;">
        <td class="center"
            style="word-break: break-word; -webkit-hyphens: none; -moz-hyphens: none; hyphens: none; border-collapse: collapse !important; vertical-align: top; text-align: center; color: #222222; font-family: Helvetica, Arial, sans-serif; font-weight: normal; font-size: 14px; margin: 0; padding: 0;">
            <table class="container"
                   style="border-spacing: 0; border-collapse: collapse; vertical-align: top; text-align: inherit; max-width: 580px; margin: 0 auto; padding: 0;">
                <tbody>
                <tr style="vertical-align: top; text-align: left; padding: 0;">
                    <td style="word-break: break-word; -webkit-hyphens: none; -moz-hyphens: none; hyphens: none; border-collapse: collapse !important; vertical-align: top; text-align: left; color: #222222; font-family: Helvetica, Arial, sans-serif; font-weight: normal; font-size: 14px; margin: 0; padding: 0;"
                    >
                        <table class="row"
                               style="border-spacing: 0; border-collapse: collapse; vertical-align: top; text-align: left; width: 100%; position: relative; display: block; background: transparent repeat center top; padding: 0;"
                        >
                            <tbody>
                            <tr style="vertical-align: top; text-align: left; padding: 0;">
                                <td class="wrapper first last"
                                    style="word-break: break-word; -webkit-hyphens: none; -moz-hyphens: none; hyphens: none; border-collapse: collapse !important; vertical-align: top; text-align: left; position: relative; color: #222222; font-family: Helvetica, Arial, sans-serif; font-weight: normal; font-size: 14px; margin: 0; padding: 10px 0 0;"
                                >
                                    <table class="twelve columns"
                                           style="border-spacing: 0; border-collapse: collapse; vertical-align: top; text-align: left; width: 580px; margin: 0 auto; padding: 0;">
                                        <tbody>
                                        <tr style="vertical-align: top; text-align: left; padding: 0;">
                                            <td style="word-break: break-word; -webkit-hyphens: none; -moz-hyphens: none; hyphens: none; border-collapse: collapse !important; vertical-align: top; text-align: left; width: 100%; color: #222222; font-family: Helvetica, Arial, sans-serif; font-weight: normal; font-size: 14px; margin: 0; padding: 0 0 10px;"
                                            >
                                                <table style="width: 100%; border-spacing: 0; border-collapse: collapse; vertical-align: top; text-align: left; padding: 0;">
                                                    <tbody>
                                                    <tr style="vertical-align: top; text-align: left; padding: 0;"
                                                    >
                                                        <td class=""
                                                            style="font-size: 1px; line-height: 0; word-break: break-word; -webkit-hyphens: none; -moz-hyphens: none; hyphens: none; border-collapse: collapse !important; vertical-align: top; text-align: left; width: 100%; color: #222222; font-family: Helvetica, Arial, sans-serif; font-weight: normal; background: transparent repeat center center; margin: 0; padding: 20px 0 10px;"
                                                        >&nbsp;
                                                        </td>
                                                    </tr>
                                                    </tbody>
                                                </table>


                                            </td>
                                            <td class="expander"
                                                style="word-break: break-word; -webkit-hyphens: none; -moz-hyphens: none; hyphens: none; border-collapse: collapse !important; vertical-align: top; text-align: left; width: 100%; visibility: hidden; color: #222222; font-family: Helvetica, Arial, sans-serif; font-weight: normal; font-size: 14px; margin: 0; padding: 0;"
                                            ></td>
                                        </tr>
                                        </tbody>
                                    </table>
                                </td>

                            </tr>
                            </tbody>
                        </table>
                    </td>
                </tr>
                </tbody>
            </table>

            <table class="row"
                   style="text-align: center; border-radius: 0; -webkit-border-radius: 0; -moz-border-radius: 0; border-spacing: 0; border-collapse: collapse; vertical-align: top; width: 100%; position: relative; background: #ffffff repeat center top; padding: 0 0;"
            >
                <tbody>
                <tr style="text-align: center; vertical-align: top; padding: 0;">
                    <td style="text-align: center; word-break: break-word; -webkit-hyphens: none; -moz-hyphens: none; hyphens: none; border-collapse: collapse !important; vertical-align: top; color: #222222; font-family: Helvetica, Arial, sans-serif; font-weight: normal; font-size: 14px; margin: 0; padding: 0;"
                    >
                        <table class="container"
                               style="border-spacing: 0; border-collapse: collapse; vertical-align: top; text-align: inherit; max-width: 580px; margin: 0 auto; padding: 0;">
                            <tbody>
                            <tr style="vertical-align: top; text-align: left; padding: 0;">
                                <td class="wrapper first last"
                                    style="word-break: break-word; -webkit-hyphens: none; -moz-hyphens: none; hyphens: none; border-collapse: collapse !important; vertical-align: top; text-align: left; position: relative; color: #222222; font-family: Helvetica, Arial, sans-serif; font-weight: normal; font-size: 14px; margin: 0; padding: 10px 0 0;"
                                >
                                    <table class="twelve columns"
                                           style="border-spacing: 0; border-collapse: collapse; vertical-align: top; text-align: left; width: 580px; margin: 0 auto; padding: 0;">
                                        <tbody>
                                        <tr style="vertical-align: top; text-align: left; padding: 0;">
                                            <td style="word-break: break-word; -webkit-hyphens: none; -moz-hyphens: none; hyphens: none; border-collapse: collapse !important; vertical-align: top; text-align: left; width: 100%; color: #222222; font-family: Helvetica, Arial, sans-serif; font-weight: normal; font-size: 14px; margin: 0; padding: 10px;"
                                            >
                                                <#--                                                    <table -->
                                                <#--                                                           style="border-collapse: collapse; border-spacing: 0; overflow: hidden; width: 100%; vertical-align: top; text-align: left; padding: 0; border: 0;">-->
                                                <#--                                                        <tbody>-->
                                                <#--                                                        <tr style="vertical-align: top; text-align: left; padding: 0;"-->
                                                <#--                                                            >-->
                                                <#--                                                            <td -->
                                                <#--                                                                style="text-align: left; word-break: break-word; -webkit-hyphens: none; -moz-hyphens: none; hyphens: none; border-collapse: collapse !important; vertical-align: top; width: 100%; color: #222222; font-family: Helvetica, Arial, sans-serif; font-weight: normal; font-size: 14px; margin: 0; padding: 0;"-->
                                                <#--                                                                >-->
                                                <#--                                                                <!--[if mso]>-->
                                                <#--                                                                <img alt='Лого.png'-->
                                                <#--                                                                     src='{link_img}'-->
                                                <#--                                                                     width='161'>-->
                                                <#--                                                                <![endif]&ndash;&gt;-->
                                                <#--                                                                <!--[if !mso]> &ndash;&gt;-->
                                                <#--                                                                <img alt="Лого.png" class="left" height="38"-->
                                                <#--                                                                     src='${link_img}'-->
                                                <#--                                                                     style="width: 161px; height: 38px; outline: none; text-decoration: none; -ms-interpolation-mode: bicubic; max-width: 100%; float: left; clear: both; display: block;"-->
                                                <#--                                                                     width="161" >-->
                                                <#--                                                                <!-- <![endif]&ndash;&gt;-->
                                                <#--                                                            </td>-->
                                                <#--                                                        </tr>-->
                                                <#--                                                        </tbody>-->
                                                <#--                                                    </table>-->


                                                <table class="table-block"
                                                       style="border-spacing: 0; border-collapse: collapse; vertical-align: top; text-align: left; padding: 0;">
                                                    <tbody>
                                                    <tr style="vertical-align: top; text-align: left; padding: 0;"
                                                    >
                                                        <td class=""
                                                            style="word-break: break-word; -webkit-hyphens: none; -moz-hyphens: none; hyphens: none; border-collapse: collapse !important; vertical-align: top; text-align: left; width: 100%; color: #222222; font-family: Helvetica, Arial, sans-serif; font-weight: normal; font-size: 14px; background: transparent repeat center center; margin: 0"
                                                        >
                                                            <p style="color: #222222; font-family: Helvetica, Arial, sans-serif; font-weight: normal; font-size: 14px; text-align: left; line-height: 1.3; margin: 0 0 10px; padding: 0;"
                                                            >&nbsp;</p>
                                                            <p style="color: #222222; font-family: Helvetica, Arial, sans-serif; font-weight: normal; font-size: 14px; text-align: left; line-height: 1.3; margin: 0 0 10px; padding: 0;"
                                                            >Спасибо за
                                                                регистрацию!<br>&nbsp;&nbsp;<br>Уважаемый
                                                                пользователь,</p>
                                                            <p style="color: #222222; font-family: Helvetica, Arial, sans-serif; font-weight: normal; font-size: 14px; text-align: left; line-height: 1.3; margin: 0 0 10px; padding: 0;"
                                                            ><strong>Ваш
                                                                    логин</strong>:&nbsp;${email}<br><strong>Ваш
                                                                    пароль</strong>: ${password}&nbsp;</p>
                                                        </td>
                                                    </tr>
                                                    </tbody>
                                                </table>


                                                <table class="button left"
                                                       style="border-spacing: 0; border-collapse: collapse; vertical-align: top; text-align: left; width: 100%; overflow: hidden; padding: 0;">
                                                    <tbody>
                                                    <tr style="vertical-align: top; text-align: left; padding: 0;"
                                                    >
                                                        <td style="word-break: break-word; -webkit-hyphens: none; -moz-hyphens: none; hyphens: none; border-collapse: collapse !important; vertical-align: top; text-align: left; width: auto !important; color: #222222; font-family: Helvetica, Arial, sans-serif; font-weight: normal; font-size: 14px; display: block; line-height: initial !important; margin: 0; padding: 0;"
                                                        >
                                                            <!--[if mso]>
                                                            <p style='line-height:0;margin:0;'>&nbsp;</p>
                                                            <v:roundrect arcsize='7%' fill='t' fillcolor='#f84343' href='http://45.147.178.196:5500/' stroke='f' strokecolor='' strokeweight='1px' style='v-text-anchor:middle;width:170px;height:36px;mso-padding-alt:0;padding:9px 20px;' xmlns:v='urn:schemas-microsoft-com:vml' xmlns:w='urn:schemas-microsoft-com:office:word'>
                                                            <w:anchorlock>
                                                            <div style='color: #FFF; font-family:sans-serif; font-size:13px; font-weight:bold; mso-line-height-rule:exactly; mso-text-raise:4px; text-align: center;'>
                                                            Перейти на сайт
                                                            </div>
                                                            </w:anchorlock>
                                                            </v:roundrect>
                                                            <![endif]-->
                                                            <!--[if !mso]>
                                                            -->
                                                            <a href="${link_sait}"
                                                               style="line-height: 16px; font-size: 16px !important; display: inline-block; border-radius: 7px; -webkit-border-radius: 7px; -moz-border-radius: 7px; color: #ffffff; text-decoration: none; font-weight: bold; font-family: Helvetica, Arial, sans-serif; text-align: center; height: 100%; width: auto; background: #f84343 repeat center center; padding: 9px 20px;">Перейти
                                                                на сайт</a>
                                                            <!-- <![endif]-->
                                                            <!--[endif]---->
                                                        </td>
                                                    </tr>
                                                    </tbody>
                                                </table>


                                            </td>
                                            <td class="expander"
                                                style="word-break: break-word; -webkit-hyphens: none; -moz-hyphens: none; hyphens: none; border-collapse: collapse !important; vertical-align: top; text-align: left; width: 100%; visibility: hidden; color: #222222; font-family: Helvetica, Arial, sans-serif; font-weight: normal; font-size: 14px; margin: 0; padding: 0;"
                                            ></td>
                                        </tr>
                                        </tbody>
                                    </table>
                                </td>

                            </tr>
                            </tbody>
                        </table>
                    </td>
                </tr>
                </tbody>
            </table>

            <table class="row"
                   style="text-align: center; border-spacing: 0; border-collapse: collapse; vertical-align: top; width: 100%; position: relative; background: #ffffff repeat center top; padding: 0;"
            >
                <tbody>
                <tr style="text-align: center; vertical-align: top; padding: 0;">
                    <td style="text-align: center; word-break: break-word; -webkit-hyphens: none; -moz-hyphens: none; hyphens: none; border-collapse: collapse !important; vertical-align: top; color: #222222; font-family: Helvetica, Arial, sans-serif; font-weight: normal; font-size: 14px; margin: 0; padding: 0;"
                    >
                        <table class="container"
                               style="border-spacing: 0; border-collapse: collapse; vertical-align: top; text-align: inherit; max-width: 580px; margin: 0 auto; padding: 0;">
                            <tbody>
                            <tr style="vertical-align: top; text-align: left; padding: 0;">
                                <td class="wrapper first last"
                                    style="word-break: break-word; -webkit-hyphens: none; -moz-hyphens: none; hyphens: none; border-collapse: collapse !important; vertical-align: top; text-align: left; position: relative; color: #222222; font-family: Helvetica, Arial, sans-serif; font-weight: normal; font-size: 14px; margin: 0; padding: 10px 0 0;"
                                >
                                    <table class="twelve columns"
                                           style="border-spacing: 0; border-collapse: collapse; vertical-align: top; text-align: left; width: 580px; margin: 0 auto; padding: 0;">
                                        <tbody>
                                        <tr style="vertical-align: top; text-align: left; padding: 0;">
                                            <td style="word-break: break-word; -webkit-hyphens: none; -moz-hyphens: none; hyphens: none; border-collapse: collapse !important; vertical-align: top; text-align: left; width: 100%; color: #222222; font-family: Helvetica, Arial, sans-serif; font-weight: normal; font-size: 14px; margin: 0; padding: 0 0 10px;"
                                            >
                                                <table class="table-block"
                                                       style="border-spacing: 0; border-collapse: collapse; vertical-align: top; text-align: left; padding: 0;">
                                                    <tbody>
                                                    <tr style="vertical-align: top; text-align: left; padding: 0;"
                                                    >
                                                        <td class=""
                                                            style="word-break: break-word; -webkit-hyphens: none; -moz-hyphens: none; hyphens: none; border-collapse: collapse !important; vertical-align: top; text-align: left; width: 100%; color: #222222; font-family: Helvetica, Arial, sans-serif; font-weight: normal; font-size: 14px; background: transparent repeat center center; margin: 0; padding: 0 10px;"
                                                        >
                                                            <p style="color: #222222; font-family: Helvetica, Arial, sans-serif; font-weight: normal; font-size: 14px; text-align: left; line-height: 1.3; margin: 0 0 10px; padding: 0;"
                                                            >С уважением,<br>команда "ClapClass"
                                                            </p>
                                                        </td>
                                                    </tr>
                                                    </tbody>
                                                </table>


                                            </td>
                                            <td class="expander"
                                                style="word-break: break-word; -webkit-hyphens: none; -moz-hyphens: none; hyphens: none; border-collapse: collapse !important; vertical-align: top; text-align: left; width: 100%; visibility: hidden; color: #222222; font-family: Helvetica, Arial, sans-serif; font-weight: normal; font-size: 14px; margin: 0; padding: 0;"
                                            ></td>
                                        </tr>
                                        </tbody>
                                    </table>
                                </td>

                            </tr>
                            </tbody>
                        </table>
                    </td>
                </tr>
                </tbody>
            </table>

        </td>
    </tr>
    </tbody>
</table>


</body>
</html>